config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'welcome/updates'
  get 'welcome/shelf'
  get 'welcome/faqs'
  get 'welcome/about'
  get 'welcome/disclaimer'

  resources :requests

  root to: 'welcome#index'

end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/request_search.rb
class RequestSearch
  attr_reader :date_from, :date_to
  
  def initialize(params)
    params ||= {}
    @date_from = parsed_date(params[:date_from], 7.days.ago.to_date.to_s)
    @date_to = parsed_date(params[:date_to], Date.today.to_s)
  end
  
  def scope
    Request.where('date BETWEEN ? AND ?', @date_from, @date_to)
  end
  
  private
  def parsed_date(date_string, default)
    Date.parse(date_string)
  rescue ArgumentError, TypeError
    default
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @search = RequestSearch.new(params[:search])
    @requests = @search.scope
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:date, :topic, :description, :user)
    end
end

app/controllers/topnav_controller.rb
class TopnavController < ApplicationController
  def index
  end

  def updates
  end

  def theshelf
  end

  def faqs
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def updates
  end

  def shelf
  end

  def faqs
  end

  def about
  end

  def disclaimer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/topnav_helper.rb
module TopnavHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PaTCH</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs" align="right">
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "Updates", welcome_updates_path %></li>
      <li><%= link_to "The Shelf", welcome_shelf_path %></li>
      <li><%= link_to "FAQ's", welcome_faqs_path %></li>
      <li><%= link_to "Requests", requests_path %></li>
      <li><%= link_to "Login", welcome_index_path %></li>
    </ul>
    <div align="center">
     <%= yield %>
    </div>
    <hr/>
    <ul class="nav nav-pills pull-right">
      <li><%= link_to "About Us", welcome_about_path %></li>
      <li><%= link_to "Disclaimer", welcome_disclaimer_path %></li>
    </ul>
  </div>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing request</h1>

<%= render 'form' %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<div class="row">
<h1>Listing requests</h1>
  <div class="pull-right range-query">
    <%= form_tag requests_path, method: :get do %>
    <%= text_field_tag 'search[date_from]', @search.date_from %>
    <%= text_field_tag 'search[date_to]', @search.date_to %>
    <%= submit_tag 'Search', class: 'btn search-button' %>
    <% end %>
  </div>
</div>

<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Topic</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.date.strftime("%I:%M %p - %A %d - %b") %></td>
        <td><%= request.topic %></td>
        <td><%= request.description %></td>
        <td><%= request.user %></td>
        <td><%= link_to 'Show', request, class: 'btn btn-mini' %></td>
        <td><%= link_to 'Edit', edit_request_path(request), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', request, method: :delete,  class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>
<br>

<%= link_to 'New Request', new_request_path %>

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

<%= link_to 'Back', requests_path %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @request.date %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @request.topic %>
</p>

<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @request.user %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>

app/views/welcome/about.html.erb
<h1>About Us</h1>
<hr/>
<p>This website is being made as an A-level Computing project/n
The purpose of the site is to provide a secure educational environment in which students can get help from their peers
and Teachers. They do this by sending a request. A teacher will then respond by creating a "Resource" found on "The Shelf".
Each resource has a comment section to give helpful tips or to ask additional questions.</p>

app/views/welcome/disclaimer.html.erb
<h1>Welcome#disclaimer</h1>
<p>Find me in app/views/welcome/disclaimer.html.erb</p>

app/views/welcome/faqs.html.erb
<h1>Welcome#faqs</h1>
<p>Find me in app/views/welcome/faqs.html.erb</p>

app/views/welcome/index.html.erb
<div align="center">
  <h1>Welcome to PaTCH</h1>
  <h4>The site filling the holes in your knowledge</h4>
  <hr/>
  <h2>Not long now! &#9731;</h2>
  <embed src="http://countdown.flashbannernow.com/xmascountdown_v4fb.swf" width="380" height="230" AllowScriptAccess="always" FlashVars="autostart=false" bgcolor="#008500" type="application/x-shockwave-flash"/>
  <hr/>
  <h2>Currently this site is being created by monkeys on macbooks</h2>
  <a href="http://alohonyai.blogspot.co.uk/2014/06/infinite-monkeys-and-alphabet.html"><img src="http://media.npr.org/assets/img/2013/12/10/istock-18586699-monkey-computer_brick-16e5064d3378a14e0e4c2da08857efe03c04695e.jpg" title="Source: To engineer is Human"/></a>
  <hr/>
</div>

app/views/welcome/shelf.html.erb
<h1>The Shelf</h1>
<p>All of the available resources are here. If you can't find what you're looking for the give a little whistle, and send a request!</p>

app/views/welcome/updates.html.erb
<h1>Welcome#updates</h1>
<p>Find me in app/views/welcome/updates.html.erb</p>